% Thu 23 Apr 17:22:05 +08 2020
function [csa, csay, csays, csy] = average_across_section(obj,weight)
	% discharge-weighted average over cross section
	% integrate over cross section
	% since width and nowidth/n is used integration is equal to averaging for Q
	% TODO, discharge weighing breaks correctness of discharge integration
	if (nargin()<2)
		w = obj.n.weight;
	else
		w = weight;
	end
	w = w./sum(w,2);

	nt = length(obj.zs);
	ny = nt/365;

	% TODO annual averages, or better wet season averages

	% annual time series, not averaged over verage over time, keep cross section
	csy = objcopy(obj);
	csy.n = structfun_deep(@(x) squeeze(nanmean(reshape_conditional(x,[365,ny,obj.nn]),2)), obj.n);

	% average across section
	csa    = objcopy(obj);
	csa.n  = structfun_deep(@(x) sum(x.*w,2), obj.n);

	f = fieldnames_deep(csa.n.qs);

	% integrate across section
	for idx=1:length(f)
		v = obj.width_.*getfield_deep(csa.n.qs,f{idx});
		csa.Qs = setfield_deep(csa.Qs,f{idx},v);
	end

	% reshape to years
	csa      = structfun_deep(@(x) reshape_conditional(x,[365,ny]), csa);

	% statistics of annual time series
	[csay, csays] = struct_avg(csa, {     ...
					    'area' ...
					  , 'discharge' ... 
					  , 'width_' ...
				  	  , 'n.a.vr' ...
				  	  , 'n.ca.vr' ...
				  	  , 'n.vr.C.dune' ...
				  	  , 'n.vr.C.total' ...
				  	  , 'n.vr.C.grain' ...
				  	  , 'n.C' ...
				  	  , 'n.d50' ...
				  	  , 'n.d90' ...
				  	  , 'n.dsus.vr' ...
				  	  , 'n.dune.vr.h' ...
				  	  , 'n.dune.karim.h' ...
				  	  , 'n.dune.vr.l' ...
				  	  , 'n.iF.vr' ...
				  	  , 'n.Fr' ...
				  	  , 'n.h' ...
				  	  , 'n.q' ...
				  	  , 'n.qs.aw' ...
				  	  , 'n.qs.vr.bed' ...
				  	  , 'n.qs.vr.total' ...
				  	  , 'n.qs.vr.sus' ...
				  	  , 'n.qs.eh' ...
				  	  , 'n.qs.karim' ...
				  	  , 'n.qs.mpm' ...
				  	  , 'n.qs.wp' ...
				  	  , 'n.qs.wu' ...
				  	  , 'n.qs.yang' ...
				  	  , 'Qs.aw' ...
				  	  , 'Qs.vr.bed' ...
				  	  , 'Qs.vr.total' ...
				  	  , 'Qs.vr.sus' ...
				  	  , 'Qs.eh' ...
				  	  , 'Qs.karim' ...
				  	  , 'Qs.mpm' ...
				  	  , 'Qs.wp' ...
				  	  , 'Qs.wu' ...
				  	  , 'Qs.yang' ...
				  	  , 'n.psus.rouse' ...
				  	  , 'n.psus.rijn' ...
				  	  , 'n.T' ...
				  	  , 'n.u' ...
				  	  , 'n.us' ...
				  	  , 'n.ws.vr' ...
				  	  , 'n.ws.default' ...
			          }, obj.p, obj.nsmooth, true);
end

